import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import { MainLayout } from '@/components/layout'
import { Metadata } from 'next';
import Loading from "./loading"
import { Suspense } from "react";

export const metadata :Metadata= {
  title:"E-commerce",
  description: 'Generated by create next app',
  icons:"https://res.cloudinary.com/dy26iktoi/image/upload/v1688595425/logo_mzoa3e.png"
  // link :"https://res.cloudinary.com/dy26iktoi/image/upload/v1688595425/logo_mzoa3e.png"
}
const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading/>}>
          <MainLayout>
            {children}  
          </MainLayout>
        </Suspense>
      </body>
    </html>
  )
}
