import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import { MainLayout } from '@/components/layout'
import { Metadata } from 'next';

export const metadata :Metadata= {
  title:"E-commerce",
  description: 'Generated by create next app',
  // link :"https://res.cloudinary.com/dy26iktoi/image/upload/v1688595425/logo_mzoa3e.png"
}
const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout>
          {children}  
        </MainLayout>
      </body>
    </html>
  )
}
